### ISSUE TITLE
links in "Get going quickly with Cyber-Dojo" section of README don't work as expected

### ISSUE THREAD

**Issue by HitLuca** [emilybache/Racing-Car-Katas#36]
Every link that points to [cyber-dojo](https://www.cyber-dojo.org/) in the `Get going quickly with Cyber-Dojo` section of `README` display `SaverService::Error` messages when opened

an example is the below screenshot 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/7645621/82440090-153b3980-9a9c-11ea-84f0-bdf6d2357733.png">

**Comment by emilybache** [comment]
sorry about that. I'll need to look into it
