### ISSUE TITLE
What is the task in the Leaderboard kata?

### ISSUE THREAD

**Issue by HelgeStenstrom** [emilybache/Racing-Car-Katas#46]
I came here via https://kata-log.rocks/race-car-katas-leaderboard. 

My problem is that I don't understand what there is to do in the  Leaderboard kata. The needed unit tests seem to already be written. What am I missing? I'm using Java; haven't looked at the other languages.

**Comment by emilybache** [comment]
Thanks for the feedback. This exercise is not perhaps as well explained as the others. There is definitely a SOLID violation in the code but perhaps it is too hard to find. Try writing some more tests and see if you can find some strange behaviour?

**Comment by HelgeStenstrom** [comment]
Now that I've started to work with it, I've found several problems, both in behaviour and in the documentation (JavaDoc, parameter names etc). Not sure how to connect them all with SOLID, but still interesting.
