### ISSUE TITLE
TirePressureMonitoringSystem: case to reset the alarm.

### ISSUE THREAD

**Issue by morpheusGitHub** [emilybache/Racing-Car-Katas#74]
Hello,

I did the Kata Car TirePressureMonitoringSystem in "java" version.

I think the case to reset the alarm is missing when you call 2 times the check function:

Alarm alarm = new Alarm()
alarm.check();
=> alarm is set to true
alarm.check();
=> Here the alarm is always on event if the sensor return false.

```
public void check()
    {
        double psiPressureValue = sensor.popNextPressurePsiValue();

        if (psiPressureValue < LowPressureThreshold || HighPressureThreshold < psiPressureValue)
        {
            alarmOn = true;
        }
    }

```

So, the code could be:

```
public void check()
    {
        double psiPressureValue = sensor.popNextPressurePsiValue();

        alarmOn = (psiPressureValue < LowPressureThreshold || HighPressureThreshold < psiPressureValue);
    }

```

Thank you.
Jérôme.

**Comment by emilybache** [comment]
The functionality described is as intended. The alarm stays on even if the pressure subsequently goes back to the normal range.

**Comment by morpheusGitHub** [comment]
Thank you very much.

I didn't read the specification because I did the kata during a training session on SOLID.
I asked to the trainer, and, because he didn't answer me about that case, I opened an issue.

Excuse me for that.
