### ISSUE TITLE
Different class name in Java project

### ISSUE THREAD

**Issue by Endless8** [emilybache/Racing-Car-Katas#76]
Hi,
in the Java project "UnicodeFileToHtmlTextConverter" the class that should be tested it has been renamed to "HtmlTextConverter", maybe it's better to name it back to "UnicodeFileToHtmlTextConverter" to be coincise with the documentation.

**Comment by emilybache** [comment]
I think most language versions use TextConverter or some simplification of the name. The original C# has the unnecessarily long name though. Probably better to update the documentation and standardize the code all to use a simpler name. So actually - I don't want to change the Java class name. Thanks for pointing out the problem though!

**Comment by codecop** [comment]
It's true. I checked. Most languages use html-text-converter, some use text-converter, Golang only has converter.go. Seems C# is outdated. @Endless8 could you update the documentation and send a PR?

**Comment by Endless8** [comment]
@codecop sure, I'll do it asap
