### ISSUE TITLE
Incorrect comparation operator

### ISSUE THREAD

**Issue by Endless8** [emilybache/Racing-Car-Katas#78]
Comparing the two string like showed in the snippet of code below it's not a good way, unless you're comparing the instance of the string, but I don't think this is the case since String class is immutable.

```java
public void send(String message)
{
    // ...
    if (message == DIAGNOSTIC_MESSAGE)
    // ...
}
```

It should be:
```java
public void send(String message)
{
    // ...
    if (message.equals(DIAGNOSTIC_MESSAGE))
    // ...
}
```

The target class is TelemetryClient of project TelemetrySystem (Java version), line 44

**Comment by emilybache** [comment]
It's probably a translation error, the original code was in C# and string comparison is done differently there. Feel free to raise a pull request that fixes this.
